import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Messages from "@/components/Messages";
import axios from "axios";
const inter = Inter({ subsets: ["latin"] });

interface Message {
  id: number
  from: string;
  text: string;
}

interface newMessage {
  from: string;
  text: string;
}

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState("something wrong! try later")

  useEffect(() => {
    fetch("https://cyf-shayanmahnam-chat-server.glitch.me/messages")
      .then((response) => response.json())
      .then((data) => {
        setMessages(data);
        setIsLoading(false)
      })
      .catch((error) => {
        console.error("Error fetching messages:", error);
      });
  }, [messages]);

  const handleSubmit = (newMessage: newMessage) => {
    const message: Message = {
      id: Date.now(),
      from: newMessage.from,
      text: newMessage.text,
    };
    console.log("Sending message:", message);
    axios
      .post(
        "https://cyf-shayanmahnam-chat-server.glitch.me/messages",
        message,
        {
          headers: { "Content-Type": "application/json" },
        }
      )
      .then((response) => {
        const data: Message = response.data;
        setMessages([...messages, data]);
        // window.location.reload(); // Reload the page
      })
      .catch((error) => {
        console.error("Error adding new message:", error);
      });
  };

  function onDeleteMessage(id: number) {
    if (id === 0) {
      console.log("Cannot delete message with ID 0.");
      alert("you can't delete this message")
      return;
    }

    axios
      .delete(`https://cyf-shayanmahnam-chat-server.glitch.me/messages/${id}`)
      .then((response) => {
        setMessages(response.data);
      })
      .catch((error) => {
        console.log(error);
      });
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header addMessage={handleSubmit} />
        <div>
          {isLoading ? (
            <div className="flex font-bold justify-center items-center">
              <svg
                className="w-20"
                version="1.1"
                id="L4"
                xmlns="http://www.w3.org/2000/svg"
                xmlnsXlink="http://www.w3.org/1999/xlink"
                x="0px"
                y="0px"
                viewBox="0 0 100 100"
                enableBackground="new 0 0 0 0"
                xmlSpace="preserve"
              >
                <circle fill="#000" stroke="none" cx="6" cy="50" r="6">
                  <animate
                    attributeName="opacity"
                    dur="1s"
                    values="0;1;0"
                    repeatCount="indefinite"
                    begin="0.1"
                  />
                </circle>
                <circle fill="#000" stroke="none" cx="26" cy="50" r="6">
                  <animate
                    attributeName="opacity"
                    dur="1s"
                    values="0;1;0"
                    repeatCount="indefinite"
                    begin="0.2"
                  />
                </circle>
                <circle fill="#000" stroke="none" cx="46" cy="50" r="6">
                  <animate
                    attributeName="opacity"
                    dur="1s"
                    values="0;1;0"
                    repeatCount="indefinite"
                    begin="0.3"
                  />
                </circle>
              </svg>

              <span>Data is loading, Please wait!</span>
            </div>
          ) : (
            <Messages messages={messages} onDeleteMessage={onDeleteMessage} />
          )}
        </div>
      </main>
    </>
  );
}
