import React, { useState, useEffect } from "react";
import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/Header";
import Messages from "@/components/Messages";

const inter = Inter({ subsets: ["latin"] });

interface Message {
  id: number;
  from: string;
  text: string;
}

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([]);

  useEffect(() => {
    fetch("https://cyf-shayanmahnam-chat-server.glitch.me/messages")
      .then((response) => response.json())
      .then((data) => {
        setMessages(data);
      })
      .catch((error) => {
        console.error("Error fetching messages:", error);
      });
  }, []);

  const handleSubmit = (newMessage: { from: string; text: string }) => {
    const message: Message = {
      id: messages.length,
      from: newMessage.from,
      text: newMessage.text,
    };
    console.log("Sending message:", message);
    fetch("https://cyf-shayanmahnam-chat-server.glitch.me/messages", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(message),
    })
      .then((response) => response.json())
      .then((data: Message) => {
        setMessages([...messages, data]);
      })
      .catch((error) => {
        console.error("Error adding new message:", error);
      });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header addMessage={handleSubmit} />
        <div>
          <Messages messages={messages} />
        </div>
      </main>
    </>
  );
}
